### ISSUE TITLE
Print stickers

### ISSUE THREAD

**Issue by ligi** [tincubeth/coordination#3]
I would love if we could print stickers for ~100DAI
Ideally we do so before ETHBerlin and CCCamp2019 to spread the word
I would suggest we do contour stickers - that are not too big 4.2cmx4.2cm?
Suggestions welcome!

**Comment by ligi** [comment]
depends on #1

**Comment by ligi** [comment]
As a supplier I would go with:

https://www.wir-machen-druck.de

they accept crypto and I already ordered stickers there once. But happy to hear about alternatives.

Regarding the format: I would love to go with a contour - for that we would need a PDF where the contour is in 100% magenta. From their website.

```
Bitte beachten Sie: 
Für den Konturschnitt benötigen wir von Ihnen in der pdf-Druckdatei eine vektorisierte Konturlinie. Bitte färben Sie diese Linie mit einer Volltonfarbe ein, die Sie cutkontur nennen und welche aus 100 Prozent Magenta besteht.
```

For the print I did for WallETH once this looked like this:
https://github.com/walleth/media/blob/master/sticker/sticker_with_contour.pdf

@olios would you be able to produce such a PDF? This would save us 50DAI that their service fee is to produce this. And I guess for a skilled designer like @olios this is just a minute of work ;-)

**Comment by ligi** [comment]
I suggest the following setup on wir-machen-druck:

![image](https://user-images.githubusercontent.com/111600/62460400-32f41800-b782-11e9-9858-288130caaa74.png)

sorry for german  - but the site does not support english as far as I know but it is the only local service that I know accepts crypto.
This would be the design (big up @olios for the work here):

![shield Logo 62px color-clear outlined Copy 11@1x](https://user-images.githubusercontent.com/111600/62472009-25e52200-b79e-11e9-874b-7f39452a0d1d.png)

alternative is:

![shield Logo 62px color-clear outlined Copy 12@1x](https://user-images.githubusercontent.com/111600/62472046-35fd0180-b79e-11e9-8131-5fe5886bcb6e.png)

but I think on e.g. a black laptop the white outline is better.
as we do not have a on-chain DAO set up currently please chime in here @ltfschoen @eshavkun @olios @JosefJ

I would first pay out of my pocket and then reimburse from the price money

would love to order this week to have them at ETHBerlinZwei and CCCamp2019

we could save ~17DAI by not checking "quality control" if we are really sure the document we create for them to print is correct

**Comment by olios** [comment]
the document has some issue while transformed in print version due to the software I used till now.
Sketchapp plugins for colour processing in CMYK makes a wrong association making the purple, in gradients of blue.

so enclosed first are the official colours as they should be processed according to different media (video, online or Print)x

<img width="813" alt="Screenshot 2019-08-07 at 17 54 31" src="https://user-images.githubusercontent.com/402953/62645035-bb71e480-b94b-11e9-9b7d-670b9f6f72e2.png">

**Comment by ltfschoen** [comment]
@ligi looks good, i'd go for the white background option.

it could be an idea to choose "writable labels" on a roll, since people sometimes have fun scribbling on the whitespace of stickers. if someone doesn't like the white background and they want the equivalent of a transparent background then they can just find some scissors and cut out the purple bits  stick them on individually. or if they want a custom background then they can just get a pen that doesn't smudge and colour in the white background with another colour.

could you keep some stickers spare for me, i won't be able to make it to either of those events :(

**Comment by ligi** [comment]
The stickers are printed - so closing this one. @ltfschoen still some left - are you in Berlin any time soon?

**Comment by ltfschoen** [comment]
@ligi yes i'll be in Berlin mid February
